ifndef::imagesdir[:imagesdir: ../images]

[[section-architecture-constraints]]
== Restricciones arquitectónicas

=== Restricciones técnicas
|===
|*Restricción* | *Descripción*
| Documentación | Se utilizará la plantilla Arc42.
| Control de versiones | Se utilizará Git y se alojará en GitHub.
| Host | Se desplegará en un host de Docker.
| API | Se utilizará una API de WikiData para obtener la información de las preguntas (fotografía, respuesta correcta y distractores). API de Gemini para la interacción con el LLM.
| Pruebas de carga | Se utilizará Gatling.
|===


=== Restricciones organizativas

Al tratarse de un proyecto en forma individual no será necesario hacer reuniones ni tomar decisiones en equipo, por lo que trataré de ir registrando todo en issues y dividir el trabajo en secciones para ir realizando el software de forma incremental sin complicaciones.
En el caso de que alguien tuviera que editar este código todo estará bien estructurado y explicado para que no hubiera problemas.